name: Static Site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Azure Login
       uses: azure/login@v1
       with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
     - name: Azure CLI script
       uses: azure/CLI@v1
       with:
         azcliversion: 2.0.72
         inlineScript: |
            az storage blob upload-batch --account-name staticazuresite -d '$web' -s website
     - name: Azure CLI script
       uses: azure/CLI@v1
       with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "staticazuresite" --name "staticazuresite" --resource-group "GHActions"
     # Azure logout 
     - name: logout
       run: |
        az logout
